#!/usr/bin/python3

#
# lightfantastic
# https://github.com/anfractuosity/lightfantastic
#

import argparse
import numpy as np
import cv2
import collections
import math
import pickle
from operator import itemgetter
from collections import defaultdict
from collections.abc import Sequence
from itertools import tee
from math import *
from lightfantastic.ids import *
from lightfantastic.spatial import *
import statistics

ZERO_COLOUR = (0, 0, 255)

# LED representation
class LED(Sequence):
    def __init__(self, x, y, tim, idv):
        self.x = x
        self.y = y
        self.idv = idv
        self.timestamp = collections.deque(maxlen=100000)
        self.timestamp.append(tim)
        self.levels = []

    def __str__(self):
        return f"({self.x},{self.y}) {self.idv}: {self.timestamp}"

    def __getitem__(self, i):
        return [self.x, self.y][i]

    def __len__(self):
        return 2

    def __eq__(self, other):
        if other == None:
            return False

        if self == None:
            return False

        return self.x == other.x and self.y == other.y

    def __hash__(self):
        return self.idv

    def addtimestamp(self, tstamp):
        self.timestamp.append(tstamp)

    def addlevel(self, level):
        self.levels.append(level)


# Detect blobs in frame
def blobdetect(frame):
    lthres = 140
    ret, frame = cv2.threshold(frame, lthres, 255, 0)
    params = cv2.SimpleBlobDetector_Params()
    params.minThreshold = lthres
    params.maxThreshold = 255
    params.filterByArea = False
    params.filterByCircularity = False
    params.filterByConvexity = False
    params.filterByInertia = False
    params.filterByColor = True
    params.blobColor = 255
    detector = cv2.SimpleBlobDetector_create(params)
    return detector.detect(frame)


def nearesti(allh, search, dist, spatial, rect, brute):
    """
    Find nearest potential LED

    :param allh: LEDs to search through
    :param search: LED to match
    :param dist: Max distance (brute mode only)
    :param spatial: Collection of collision rectangles (non-brute mode only)
    :param rect: Current rectangle
    :param brute: Boolean: brute-force mode? (vs collision detection)
    """

    found = []
    if brute:
        dist2 = dist * dist
        for idv in allh:
            ldv = allh[idv]
            dst2 = (search.x - ldv.x) ** 2 + (search.y - ldv.y) ** 2
            if dst2 < dist2:
                dst = math.sqrt(dst2)
                found.append((dst, ldv))
        return sorted(found, key=itemgetter(0))
    else:
        for idv in spatial.potential_collisions(rect, search):
            found.append((None, idv))
            break
        return found


# Sliding window
def window(iterable, size):
    iters = tee(iterable, size)
    for i in range(1, size):
        for each in iters[i:]:
            next(each, None)
    return zip(*iters)


# Convert list representing binary, to integer value
def binary(arr):
    m = 0
    s = 0
    for o in arr:
        s = s + (o * (2 ** m))
        m = m + 1
    return s


# Manchester decode
def mancdec(arr):
    out = []
    for i in range(0, len(arr), 2):
        if arr[i : i + 2] == [0, 1]:
            out.append(0)
        elif arr[i : i + 2] == [1, 0]:
            out.append(1)
    return out


# Calculate CRC checksum
def crc(val):
    s = ""
    for b in val:
        s = s + str(b)
    return binascii.crc32(s.encode("ascii")) % 256


# Get blobs from video frames
def getblobs(videofile, brute):

    spatial = SpatialHash()
    cap = cv2.VideoCapture(videofile)
    official_fps = cap.get(cv2.CAP_PROP_FPS)
    potentialleds = {}
    fcount = 0
    calc_fps = 0
    frameno = 0
    old = -1
    uid = 0

    while True:

        # Calculate framerate
        timestamp = int(cap.get(cv2.CAP_PROP_POS_MSEC))
        fcount = fcount + 1
        if fcount > calc_fps:
            frameno = frameno + 1
            if timestamp > old + 1000 and frameno > 1:
                calc_fps = frameno
                frameno = 0
                old = timestamp

        ret, frame = cap.read()
        if type(frame) != np.ndarray:
            break

        # Find blobs, and draw them on image
        lastf = frame
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
        blobs = blobdetect(frame)
        im = cv2.drawKeypoints(
            frame,
            blobs,
            np.array([]),
            ZERO_COLOUR,
            cv2.DRAW_MATCHES_FLAGS_DRAW_RICH_KEYPOINTS,
        )

        cv2.imshow("Video", im)

        if cv2.waitKey(1) & 0xFF == ord("q"):
            break

        fps = official_fps
        cur = []
        if fps > 20:

            for k in blobs:
                x = k.pt[0]
                y = k.pt[1]
                cur.append((x, y, k.size))

            # Process blobs in current frame
            for l in cur:

                uid = uid + 1
                search_led = LED(l[0], l[1], timestamp, uid)
                rect = Rect(x1=l[0] - 1, y1=l[1] - 1, x2=l[0] + 1, y2=l[1] + 1)
                nearest = nearesti(potentialleds, search_led, 8, spatial, rect, brute)

                # If no previous potential LED, add this LED to potential LEDs
                if len(nearest) == 0:
                    potentialleds[search_led.idv] = search_led
                    spatial.add_rect(rect, search_led)
                    continue

                # If we found a potential previous LED, add this timestamp to it
                add = True
                for allv in nearest:
                    if allv[1].timestamp[-1] != timestamp:
                        o = allv[1]
                        o.addtimestamp(timestamp)
                        o.x = search_led.x
                        o.y = search_led.y
                        potentialleds[o.idv] = o
                        add = False
                        break

                if add:
                    potentialleds[search_led.idv] = search_led
                    spatial.add_rect(rect, search_led)

    cap.release()
    return lastf, potentialleds, fps


# For each candidate, store the average level around it in every frame.
def getlevels(movie, potentialleds):
    cap = cv2.VideoCapture(movie)
    while True:
        ret, frame = cap.read()
        if type(frame) != np.ndarray:
            break
        frame = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)

        for idv in potentialleds:
            led = potentialleds[idv]
            patch = frame[int(led.y)-1:int(led.y)+2, int(led.x)-1:int(led.x)+2]
            level = np.average(patch)
            led.addlevel(level)

    cap.release()


def decodeleds(potentialleds, clock, debounce, debug):
    count_g20 = 0
    count_preamble = 0
    count_crc = 0
    tagged_leds = {}
    framethreshold = fps / clock

    for key in potentialleds:
        if debug:
            print(f"Key {key}")
        t = potentialleds[key].timestamp
        led = potentialleds[key]

        if len(t) > 20:
            count_g20 += 1

            if debug:
                print(f"Flevels {led.levels}")

            # Threshold by median
            median = statistics.median(led.levels)
            levels = [1 if f > median else 0 for f in led.levels]

            if debounce:
                # Debounce levels
                debounced = []
                for i in range(len(levels)-2):
                    if levels[i:i+3] == [1,0,1]:
                        debounced.append(1)
                    elif levels[i:i+3] == [0,1,0]:
                        debounced.append(0)
                    else:
                        debounced.append(levels[i+1])

                if debug:
                    print(f"Debounced {debounced}")
                levels = debounced

            if debug:
                # Histogram of run lengths, to help guess clock rate
                lengths = {}
                last = None
                count = 0
                for b in levels:
                    if last != b:
                        if count not in lengths:
                            lengths[count] = 1
                        else:
                            lengths[count] += 1
                        last = b
                        count = 1
                    else:
                        count += 1
                for l in sorted(lengths):
                    bar = lengths[l] * "]"
                    print(f"{l:3}: {bar:40} {lengths[l]:2}")

            # Extract raw bits
            bits = []
            count = 0
            state = 1
            for i in range(len(levels)):
                if levels[i] == state:
                    count += 1
                else:
                    numperiods = int(count / framethreshold + 0.5)
                    bits.extend(numperiods * [state])
                    state = levels[i]
                    count = 0

            if debug:
                bits_s = "".join(["1" if b else "o" for b in bits])
                print(f"Bits: {bits_s}")
            found = False

            most = defaultdict(int)
            for x in window(bits, 68):
                # Check for preamble
                n2 = [z for z in x]
                pre = n2[:32]

                if pre == mp:
                    # Decode
                    if debug:
                        print(f"mp key {key} {bits}")
                    count_preamble += 1
                    m = mancdec(n2)
                    check = binary(m[-8:])
                    bbb = binary(m[16 : 16 + 10])

                    # Check CRC
                    if crc(m[0 : 16 + 10]) == check:
                        count_crc += 1
                        most[bbb] = most[bbb] + 1
                        found = True
                        break

            last = 0
            idv = -1
            for k in most:
                if most[k] > last:
                    idv = k
                    last = most[k]

            if found:
                # Add this LED to output set
                tup = (int(led.x), int(led.y), idv)
                tagged_leds[idv] = tup

    print(f"Candidates with at least 20 frames: {count_g20}\nPreambles matched: {count_preamble}\nCorrect CRC: {count_crc}")

    return tagged_leds


if __name__ == "__main__":

    parser = argparse.ArgumentParser(description="CLI for lightfantastic")
    parser.add_argument(
        "--movie",
        dest="movie",
        type=argparse.FileType("r"),
        help="Filename of video of lights",
        required=True,
    )
    parser.add_argument(
        "--out",
        dest="out",
        type=str,
        help="Filename to output position of lights",
        required=True,
    )
    parser.add_argument(
        "--brute",
        dest="brute",
        nargs="?",
        default=False,
        help="Bruteforce find nearby LEDs",
    )
    parser.add_argument(
        "--intermediate",
        dest="intermediate",
        type=str,
        default="intermediate.p",
        help="Filename to hold intermediate state",
    )
    parser.add_argument(
        "--rescan",
        dest="rescan",
        action="store_true",
        help="Use intermediate state rather than loading movie file",
    )
    parser.add_argument(
        "--debounce",
        dest="debounce",
        action="store_true",
        help="Apply simple debouncing to clean up bitstream before decoding",
    )
    parser.add_argument(
        "--debug",
        dest="debug",
        action="store_true",
    )
    parser.add_argument(
        "--clock",
        dest="clock",
        type=float,
        help="Bit clock rate in hertz",
        default=4.8,
    )

    args = parser.parse_args()
    movie = args.movie.name
    args.movie.close()
    brute = not (args.brute == False)
    mp = IDs(0).manchester(IDs(0).preamble)

    if not args.rescan:
        # Find all the blobs
        lastf, potentialleds, fps = getblobs(movie, brute)

        # Now reload the video, and get the levels for each possible LED
        getlevels(movie, potentialleds)

        pickle.dump((lastf, potentialleds, fps), open(args.intermediate, "wb"))

    (lastf, potentialleds, fps) = pickle.load(open(args.intermediate, "rb"))
    print(f"Video: {fps}fps")

    # Find valid LEDs
    tagged_leds = decodeleds(potentialleds, args.clock, args.debounce, args.debug)

    # Display tagged LEDs on last processed video frame
    numleds = 0
    for led_id in tagged_leds:
        numleds += 1
        # print(led_id)
        led_pos = tagged_leds[led_id]
        font = cv2.FONT_HERSHEY_SIMPLEX
        cv2.putText(
            lastf,
            str(led_id),
            (int(led_pos[0]), int(led_pos[1])),
            font,
            0.3,
            (0, 0, 255),
            1,
            cv2.LINE_AA,
        )

    print(f"Found {numleds} from {len(potentialleds)} candidates")

    pickle.dump(tagged_leds, open(args.out, "wb"))

    cv2.imshow("Video", lastf)
    cv2.waitKey(0)
    cv2.destroyAllWindows()
